language: ruby
rvm:
  - 2.1

before_script:
  - chmod +x ./scripts/cibuild
script: ./scripts/cibuild
branches:
  only:
    - jekyll
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
