# Site settings
title: kheiakiyama's CV 
description: kheiakiyama's CV
favicon: /assets/img/avatar.png
baseurl: .
url: https://profile.kheiakiyama.com
rss_url: /pages/atom.xml
google_analytics: UA-46111689-1

# Build settings
markdown: kramdown

exclude: [vendor, terraform, Gemfile, Gemfile.lock, proxies.json, README.md, travis.sh]

# Author settings
author:
  name: kheiakiyama
  title: Azure Solution Architect
  address: Sumida-Ku, Tokyo
  email: kheiakiyama#gmail.com
  link: https://cv.kheiakiyama.com
  github: kheiakiyama
  blog: kheiakiyama.hateblo.jp
  linkedin: kheiakiyama
  twitter: kheiakiyama
  medium: kheiakiyama
  gavatar: /resumecard/assets/img/avatar.JPG
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: ISAO Ltd
      location: Tokyo, Japan
      title: Azure Solution Architect
      started: 2017
      duration: (2017 - Present)
      description: As pre-sales engineer and cloud solution architect I am helping customers design and implement customer systems.
    - work2:
      company: Kensetsu System Ltd
      location: Shizuoka, Japan
      title: Programmer
      started: 2005
      duration: (2005 - 2016)
      description: For the first 2 years, I implemented functions as a programmer with about 3-5 members. After that, I was in charge of specification review, design and team building as a team leader. In the last three years I have been involved in cloud service technology selection and web service development using Azure. In addition to Windows-based technologies, I also experienced development work using OSS technology, and selected and introduced Web services, built servers, and developed Web services for their own development department.
  communityActivity:
    - work:
      title: Tech Summit 2018
      year: 2018
      duration: Nov 2018
      speaker: true
      link: https://www.event-marketing.jp/events/mstechsummit/2018/download/freesess.aspx#CI26
      description: In Tech Summit 2018, talk about case study of Microsoft Azure.
    - work:
      title: Tech Summit 2018
      year: 2018
      duration: Nov 2018
      speaker: true
      link: https://blog.isao.co.jp/techsummit-2018-datafactory-handson/
      description: In Tech Summit 2018, handson about Azure Data Factory.
    - work:
      title: de:code 2018
      year: 2018
      duration: May 2018
      speaker: true
      link: https://www.microsoft.com/ja-jp/events/decode/2018
      description: In de:code2018, talk about case study of Microsoft Azure.
    - work:
      title: Nikkei Cloud First - Azure API Management
      year: 2018
      duration: Feb 2018
      writing: true
      link: http://tech.nikkeibp.co.jp/it/atclncf/service/00031/011700002/
      description: Writing service evaluation about Azure API Management.
    - work:
      title: Engineer Lab Fukuoka #1
      year: 2018
      duration: Jan 2018
      speaker: true
      link: https://www.slideshare.net/ssuser1b3e44/20180119ai
      description: In Engineer Lab Fukuoka #1, talk about cloud technology.
    - work:
      title: Nikkei Cloud First - Azure Data Factory
      year: 2017
      duration: Nov 2017
      writing: true
      link: http://tech.nikkeibp.co.jp/it/atclncf/service/00028/101600002/
      description: Writing service evaluation about Azure Data Factory.
  educationHistory:
    - education1:
      organization: Shizuoka Industrial Technology College
      location: Shizuoka, Japan
      degree: Computer Science College
      major: Computer Science
      started: 2003
      duration: (2003 - 2005)
      description: 
  languages:
    - language1:
      name: Japanese
      proficiency: Native
    - language2:
      name: English
      proficiency: Limited TOEIC:720
  programmingSkills:
    - skill1:
      name: C#
      percentage: 80%
    - skill2:
      name: ASP.NET MVC
      percentage: 50%
    - skill3:
      name: JavaScript
      percentage: 60%
    - skill4:
      name: Azure
      percentage: 95%
    - skill5:
      name: DevOps
      percentage: 90%
