name: "deploy"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  deploy: # make sure build/ci work properly
    runs-on: ubuntu-latest
    env:
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
    steps:
    - uses: actions/checkout@v2
    - uses: kheiakiyama/install-azcopy-action@v1
      with: 
        version: 'v10'
    - run: azcopy --version | grep 'azcopy'
    - uses: eregon/use-ruby-action@v1
      with:
        ruby-version: 2.5.7
    - name: jekyll build
      run: |
        ruby --version
        pwd
        ls -l
        sudo apt-get update
        sudo apt-get install libxml2
        gem install nokogiri -v '1.10.7' --source 'https://rubygems.org/'
        bundle install
        ./scripts/cibuild
    - run: azcopy --version | grep 'azcopy'