name: "deploy"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  deploy: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: kheiakiyama/install-azcopy-action@v1
      with: 
        version: 'v10'
    - run: |
        which azcopy
        pwd
        azcopy --version | grep 'azcopy'
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.5
    - run: |
        which azcopy
        pwd
        azcopy --version | grep 'azcopy'
    - name: Set up bundler
      run: gem install bundler
    - run: |
        which azcopy
        pwd
        azcopy --version | grep 'azcopy'
    - name: nokogiri dependencies
      run: |
        ruby --version
        pwd
        ls -l
        echo $LANG
        timedatectl
        sudo apt-get update
        sudo apt-get install libxml2 libxslt1-dev
        echo $LANG
        timedatectl
    - run: |
        which azcopy
        pwd
        azcopy --version | grep 'azcopy'
    - name: jekyll build
      run: |
        bundle install --jobs 4
        ./scripts/cibuild
      env:
        NOKOGIRI_USE_SYSTEM_LIBRARIES: false
    - run: |
        which azcopy
        pwd
        azcopy --version | grep 'azcopy'
